//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaViajeros.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        public int MovimientoID { get; set; }
        public int ViajeroID { get; set; }
        public int DocumentoID { get; set; }
        public int PuntoControlOrigen { get; set; }
        public int PuntoControlDestino { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string TipoSolicitud { get; set; }
    
        public virtual Documentos Documentos { get; set; }
        public virtual PuntosDeControl PuntosDeControl { get; set; }
        public virtual PuntosDeControl PuntosDeControl1 { get; set; }
        public virtual Viajeros Viajeros { get; set; }
    }
}
