//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaViajeros.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntosDeControl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PuntosDeControl()
        {
            this.Movimientos = new HashSet<Movimientos>();
            this.Movimientos1 = new HashSet<Movimientos>();
        }
    
        public int PuntoControlID { get; set; }
        public string NombreControl { get; set; }
        public string Ubicacion { get; set; }
        public string Descripcion { get; set; }
        public int UsuarioID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimientos> Movimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimientos> Movimientos1 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
